export const EDIT_INPUT_TITLE = 'EDIT_INPUT_TITLE';
export const EDIT_INPUT_CONTENT = 'EDIT_INPUT_CONTENT';
export const EDIT_INPUT_CATEGORY = 'EDIT_INPUT_CATEGORY';
export const EDIT_INPUT_HASTAG = 'EDIT_INPUT_HASTAG';

export const EDIT_INPUT_CATEGORY_LIST = 'EDIT_INPUT_CATEGORY_LIST';

export const EDIT_COVER_IMAGE = 'EDIT_COVER_IMAGE';
